[package]
name = "kd_tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_approx_eq = "*"
rand = "*"
serde = "*"
kdam = "*"
byteorder = "1.4.3"
ascii = "*"
